[package]
name = "rogulike"
authors = ["Alper TimuÃ§in Akyol <akyolalper101@gmail.com>"]
version = "0.1.0"
edition = "2024"

[dependencies]
rltk = {version = "0.8.0" }
getrandom = {version = "0.2", features = ["js"] }

