[package]
name = "rogulike"
authors = ["Alper Timu√ßin Akyol <akyolalper101@gmail.com>"]
version = "0.1.0"
edition = "2024"

[dependencies]
rltk = {version = "0.8.0" }
specs = "0.20.0"
specs-derive = "0.4.1"

